version: '3.5'
services:
  backend:
    build: ./bff
    image: canlease-bff:latest
    volumes:
      - ./bff:/usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - IDENTITY_SESSION_COOKIE_NAME
      - PORT=${BFF_PORT}
      - BFF_URL=http://localhost:${BFF_PORT}
      - FRONTEND_URL=https://localhost:${FRONTEND_PORT}
      - FRONTEND_DOMAIN=${DOMAIN}
      - IDENTITY_URL=https://app.dev-canlease.spindl.dev/identity
      - DATA_URL=https://app.dev-canlease.spindl.dev/data
      - BEARER_TOKEN=${BEARER_TOKEN}
      - SALESFORCE_API_URL=${SALESFORCE_API_URL}
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
  frontend:
    build: ./frontend
    image: canlease-fe:latest
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_BFF_URL=http://localhost:${BFF_PORT}
      - REACT_APP_SESSION_COOKIE_NAME=${IDENTITY_SESSION_COOKIE_NAME}
      - REACT_APP_DOMAIN=${DOMAIN}
      - REACT_APP_FRONTEND_URL=https://localhost:${FRONTEND_PORT}
      - REACT_APP_IS_DEV=${IS_DEV}
      - REACT_APP_GTM_ID=${GTM_ID}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    stdin_open: true