version: '3.5'

services:
  db:
    image: registry.spindl.dev/spindl-postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - DB_IDENTITY_ENABLED
      - DB_IDENTITY_NAME
      - DB_IDENTITY_USER
      - DB_IDENTITY_PASSWORD
      - POSTGRES_PORT
      - DB_RECONNECT_TRIES
      - DB_RECONNECT_INTERVAL
    volumes:
      - ./.docker/postgresql-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  backend:
    build: ./bff
    image: ${appName}-bff:latest
    volumes:
      - ./bff:/usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - IDENTITY_SESSION_COOKIE_NAME
      - IDENTITY_URL
      - PORT=${BFF_PORT}
      - BFF_URL=http://localhost:${BFF_PORT}
      - FRONTEND_URL=https://localhost:${FRONTEND_PORT}
      - FRONTEND_DOMAIN=${DOMAIN}

    ports:
      - "${BFF_PORT}:${BFF_PORT}"

  frontend:
    build: ./frontend
    image: ${appName}-fe:latest
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_BFF_URL=http://localhost:${BFF_PORT}
      - REACT_APP_SESSION_COOKIE_NAME=${IDENTITY_SESSION_COOKIE_NAME}
      - REACT_APP_DOMAIN=${DOMAIN}
      - REACT_APP_FRONTEND_URL=https://localhost:${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    stdin_open: true

  identity:
    depends_on:
      - db

    # DEV
    # build: "${IDENTITY_PATH}/."
    # image: spindl-identity:latest
    # volumes:
    #   - "${IDENTITY_PATH}:/usr/src/app"
    # command: "npm run start:dev"

    # PROD
    image: registry.spindl.dev/spindl-identity:latest
    command: "npm run start"

    ports:
      - "${IDENTITY_PORT}:${IDENTITY_PORT}"
    environment:
      - SERVICE_BASE_PATH=identity
      - BACKEND_PORT=${IDENTITY_PORT}

      - POSTGRES_HOST=db
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_IDENTITY_NAME}
      - POSTGRES_USER=${DB_IDENTITY_USER}
      - POSTGRES_PASSWORD=${DB_IDENTITY_PASSWORD}

      - IDENTITY_SESSION_COOKIE_NAME=${IDENTITY_SESSION_COOKIE_NAME}
      - TOKEN_ISSUER=${IDENTITY_URL}
      - TOKEN_AUDIENCE=${SPINDL_APP_URL}
      - TOKEN_EXPIRY=${IDENTITY_TOKEN_EXPIRY}
      - TOKEN_MAX_AGE=${IDENTITY_TOKEN_MAX_AGE}
      - IDENTITY_API_URL=${IDENTITY_URL}
      - DOMAIN=${DOMAIN}

      - SENDGRID_API_KEY
      - SENDGRID_FROM_EMAIL
      - SENDGRID_SIGN_UP_TEMPLATE_ID
      - SENDGRID_CONFIRM_EMAIL_TEMPLATE_ID
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID
      - RESET_PASSWORD_TOKEN_EXPIRY

      - STATE_TOKEN_EXPIRY=360000
