FROM node:14-alpine as builder

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm prune --production

FROM node:14-alpine

WORKDIR /usr/src/app

COPY --from=builder /app/package.json /usr/src/app/package.json
COPY --from=builder /app/build /usr/src/app/build
COPY --from=builder /app/node_modules /usr/src/app/node_modules

CMD [ "npm", "run", "start" ]